--- 
- 
  hosts: localhost
  tasks: 
    - 
      command: "dcos marathon app add shipconsole.json"
      name: "Deploy Mesos Application"
      register: docker
    - 
      debug: var=docker.stdout
